exports.ausbildungs = [
  {
    id: 1,
    type: 'Educatie',
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    type: 'Internship',
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    type: 'Voluntariat',
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    type: 'Educatie',
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    type: 'Internship',
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    type: 'Voluntariat',
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    type: 'Work Experience',
    userId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    type: 'Education',
    userId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
