exports.details = [
  {
    id: 1,
    title: 'Johannes Honterus',
    position: 'Elev',
    location: 'Brasov',
    description:
      'Am fixat cunostintele de baza pentru diferite materii si mi-am perfectionat limba germana',
    startyear: 2014,
    endyear: 2018,
    ausbildungId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: 'Kinderspielstadt',
    position: 'Voluntar',
    location: 'Barcut',
    description:
      'Tabara internationala pe limba germana unde se simula viata de adult intr-un oras pentru copii.',
    numberOfMonths: 1,
    startyear: 2017,
    endyear: 2017,
    ausbildungId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: 'Principal33',
    position: 'Intern',
    location: 'Brasov',
    description:
      'Internship platit unde am invatat tehnologiile .Net, C# si Vue.js, dar si metodologii precum Agile sau ITIL',
    startyear: 2020,
    endyear: 2021,
    ausbildungId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: 'Facultatea de Matematica si Informatica',
    position: 'Student',
    location: 'Brasov',
    description:
      'Invatarea conceptelor din informatica, baza de date, OOP, algoritmi.',
    startyear: 2018,
    endyear: 2021,
    ausbildungId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    title: 'Facultatea de Matematica si Informatica',
    position: 'Student',
    location: 'Brasov',
    description: 'Specializare: Informatica',
    startyear: 2018,
    endyear: 2021,
    ausbildungId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    title: 'Dr. Ioan Mesota',
    position: 'Elev',
    location: 'Brasov',
    description: 'Profil: Matematica Informatica, intensiv Informatica',
    startyear: 2014,
    endyear: 2018,
    ausbildungId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    title: 'Principal33',
    position: 'Intern',
    location: 'Brasov',
    description:
      'Internship platit unde am invatat tehnologiile .Net, C# si Vue.js, dar si metodologii precum Agile sau ITIL',
    startyear: 2020,
    endyear: 2021,
    ausbildungId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    title: 'Trimble',
    position: 'Intern',
    location: 'Brasov',
    description:
      'In cadrul internship-ului am invatat tehnologii precum Angular si .NET Core, la final realizand un proiect care a inglobat cunostintele acumulate',
    startyear: 2020,
    endyear: 2020,
    numberOfMonths: 1,
    ausbildungId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    title: 'BEST',
    position: 'Voluntar',
    location: 'Brasov',
    description:
      'Participarea la diverse proiecte ce implica comunicarea cu participanti internationali si dezvoltarea acestora.',
    numberOfMonths: 1,
    startyear: 2019,
    endyear: 2020,
    ausbildungId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    title: 'University Of Transilvania, Brasov',
    position: 'Student (BSc)',
    location: 'Brasov, Romania',
    description: 'BSc in Applied Computer Science (German Language)',
    startyear: 2018,
    endyear: 2021,
    ausbildungId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    title: 'University of Heilbronn',
    position: 'Student (BSc)',
    location: 'Heilbronn, Germany',
    description: 'BSc in Software Engineering (Erasmus+)',
    startyear: 2019,
    endyear: 2020,
    ausbildungId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    title: 'Principal33 Solutions',
    position: 'Software Developer Intern',
    location: 'Brasov, Romania',
    description: 'Gained knowledge of AGILE methodologies, ITIL, .Net. Improved skills of CSS & Html, learned Vue.js and SALESFORCE',
    startyear: 2020,
    endyear: 2020,
    ausbildungId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    title: 'Elektrobit',
    position: 'Summer Intern',
    location: 'Brasov, Romania',
    description: 'Developed and designed user-friendly, interactive interfaces with the main field of use in the automotive industry. Debugged, tested and monitored user interfaces during simmulation. Used GIT for version control.',
    startyear: 2020,
    endyear: 2020,
    ausbildungId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    title: 'Siemens',
    position: 'Spring Intern',
    location: 'Brasov, Romania',
    description: 'Image processing using artificial intelligence',
    startyear: 2020,
    endyear: 2020,
    ausbildungId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    title: 'Pentalog',
    position: 'Summer Trainee',
    location: 'Brasov, Romania',
    description: 'Acquired knowledge of OOP concepts. Developed strong problem-solving skills. Improved kowledge of C# fundamentals.',
    startyear: 2017,
    endyear: 2017,
    ausbildungId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
