exports.details = [
  {
    id: 1,
    title: 'Johannes Honterus',
    position: 'elev',
    location: 'Brasov',
    description: 'Liceu pe limba germana',
    startyear: 2014,
    endyear: 2018,
    ausbildungId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: 'Principal33',
    position: 'student',
    location: 'Brasov',
    description: 'Paid internship',
    startyear: 2020,
    endyear: 2021,
    ausbildungId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
