exports.skills = [
  {
    id: 1,
    skill: 'javascript',
    rating: 5,
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    skill: 'c#',
    rating: 3,
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    skill: 'java',
    rating: 3,
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    skill: 'python',
    rating: 4,
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    skill: 'C++',
    rating: 4,
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    skill: 'C#',
    rating: 3,
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    skill: 'java',
    rating: 3,
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    skill: 'HTML',
    rating: 4,
    userId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
