exports.users = [
  {
    id: 1,
    lastName: 'Birghisan',
    firstName: 'Teodor-Octavian',
    email: 'birghisanteodor@yahoo.com',
    age: 21,
    occupation: 'Software Engineer',
    hobby:
      'Pe langa hobby-ul, care imi ocupa majoritatea timpului, programarea, imi place in timpul liber sa fac activitati care sunt total opuse. Spre exemplu, iarna, incerc sa merg la ski cu fiecare ocazie, vara incerc trasee cu bicicleta pana unu dintre noi se rupe, sau o excursie de cateva zile. Cand vremea nu imi permite astfel de activitati, prefer sa citesc sau eventual sa ma joc pe PC. Totodata, incerc pe cat posibil sa nu ratez petreceri sau evenimente, care mi se par mai speciale sau care mi-ar aduce o experienta noua.',
    telephone: '0727883745',
    linkedIn: 'https://www.linkedin.com/in/teodor-birghisan-5585881b8/',
    password: '1234',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    lastName: 'Puchianu',
    firstName: 'Alexandra-Georgiana',
    email: 'puchianu_alexandra@yahoo.com',
    age: 22,
    occupation: 'Software Developer',
    hobby: 'In timpul liber imi place sa descopar noi pasiuni. Printre hobby-urile mele se enumara si dansul, drumetiile, schiatul, mersul cu bicicleta si multe altele.',
    telephone: '0749816360',
    linkedIn: 'https://www.linkedin.com/in/alexandra-puchianu-433a381b4/',
    password: '1234',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
